### PR TITLE
Create a contribution heatmap for the README

### PR DESCRIPTION
**Pull request by dhimmel**
Eventually would like continuous analysis to update this plot.

### CODE REVIEW

**Comment by dhimmel** [comment]
Note that one issue I ran into was [GitHub's rate limit](https://developer.github.com/v3/#rate-limiting) for unauthenticated API queries -- 60 per hour per IP address. This could potentially cause problems on a CI server where other unathenticated builds had exhausted the API limits.

**Comment by stephenshank** [comment]
May be worth noting that this is for unauthenticated requests... it is possible to increase it to 5000 per hour if you authenticate.

**Comment by cgreene** [comment]
I have reviewed the code & figure. :+1: LGTM! Exciting to see this quantified!

**Comment by dhimmel** [comment]
@cgreene, I made some additional changes in a new commit (391487f24ebb8464d4ab19ef79ae378f6364c704). Can you review again?

**Comment by cgreene** [comment]
I have reviewed the table. I did not manually verify numbers, but code + table :+1: LGTM.

**Pull request merged**
