### PR TITLE
Adds Jeff Riegler's Cognoma logo.

### PR DESCRIPTION
**Pull request by stephenshank**
Adds a logo designed by Jeff Riegler; see #21.

I included only the `.svg` since there are issues with the `.png` that I created. Adding color might be better handled by someone with more experience in design. I am happy to also include my other files, should anyone find it useful.

### CODE REVIEW

**Review by dhimmel — COMMENTED** [review]
Nice. Looks like you nailed the git commit author intricacy!

Let's make a `logo` directory. You can

``` sh
git mv logo_jriegler.svg logo/cognoma-bw.svg
```

> I included only the .svg since there are issues with the .png that I created. Adding color might be better handled by someone with more experience in design. I am happy to also include my other files, should anyone find it useful.

Let's get this PR merged. Then we can have you create another pull request with your modifications.

**Comment by dhimmel** [comment]
@stephenshank nice. One last question before merging. Did Jeff use any sort of program to design this, and if so should we also upload that session file?

**Comment by stephenshank** [comment]
Just got the original file from him, which was created using Adobe Illustrator. It's about 1.6 MB, and it doesn't get much smaller when I compress it. I can add it to this repository, or upload it somewhere and provide a link. Thoughts?

**Comment by dhimmel** [comment]
1.6 MB is fine! Let's upload it uncompressed to `logo/cognoma-bw.ai`.

**Review by dhimmel — APPROVED** [review]

**Comment by cgreene** [comment]
1.6 MB should be fine for github. :+1:

**Comment by dhimmel** [comment]
I converted the SVG to PNG for applications that don't support SVG:

cognoma-bw

**Comment by dhimmel** [comment]
Just wanted to note that the current logo gets the double helix chirality correct. DNA is right-handed [as described here](http://sandwalk.blogspot.ca/2015/03/on-handedness-of-dna.html). Wanted to make sure, since many graphic designers overlook this nuance and inevitably [someone notices](https://twitter.com/sksilverman/status/784375046211010560). Also [see this tweet](https://twitter.com/orchidhunter/status/735512917785743360).

**Pull request merged**
