### PR TITLE
Update on 2016-10-31

### PR DESCRIPTION
**Pull request by dhimmel**
Recompiles contribution stats.

Adds cognoml repo to README.md.

@cgreene, I made `master` a protected branch that requires a positive review. Excited to see how this works, feel free to review.

### CODE REVIEW

**Comment by dhimmel** [comment]
protected-review

> @cgreene, I made master a protected branch that requires a positive review. Excited to see how this works

Too bad we can't make it accept reviews from any Cognoma organization member. I guess we should give write access to more people... especially since now the damage is limited from a lone actor (:

**Review by cgreene — COMMENTED** [review]
Does this include the logo contribution? It doesn't look like any new names showed up.

**Comment by dhimmel** [comment]
> Does this include the logo contribution? It doesn't look like any new names showed up.

Ahh crap! GitHub's squash feature replaced Jeff Riegler as the author with @stephenshank. PR (https://github.com/cognoma/cognoma/pull/38) was good but squashed commit (74190608292036085cfa148c90e64b4d8040ed28) was not https://github.com/cognoma/cognoma/pull/38.

This issue will be fixed when Jeff Riegler shows up in [this API call](https://api.github.com/repos/cognoma/cognoma/contributors). Fixing the commit author will be necessary -- maybe not sufficient (we may need Jeff Riegler to make a GitHub account).

**Comment by dhimmel** [comment]
@cgreene I propose that I unprotect this branch, fix the commit author, and force push to master. Then reprotect the branch.

**Comment by cgreene** [comment]
@dhimmel : I agree with your proposal to fix the commit author.

**Comment by dhimmel** [comment]
> @cgreene I propose that I unprotect this branch, fix the commit author, and force push to master. Then reprotect the branch.

I did the deed! However, the GitHub API call is still returning 1 contribution from `stephenshank`. Since the deed should have changed the commit hash, this [shouldn't be happening](https://developer.github.com/v3/repos/statistics/):

> Repository statistics are cached by the SHA of the repository's default branch, which is usually master; pushing to the default branch resets the statistics cache.

Let's check back tomorrow.

**Comment by dhimmel** [comment]
Okay the GitHub API contributor query appears to be up to date in my latest commit 117960ba2142f9e77670ba012b5f7c206680981a. Jeff Riegler won't show up unless he makes a GitHub account that registers his email address (@stephenshank not sure whether Jeff wants to do this).

@cgreene Does this look ready to merge?

**Review by cgreene — APPROVED** [review]
I approve of this PR given the resolution on the logo.

**Pull request merged**
